"""Persistence contracts for engineering extraction review."""

from typing import Protocol
from backend.domain.engineering_review import ConfirmedCommand, EngineeringReview, ExtractionRun


class EngineeringReviewRepository(Protocol):
    def discover_extraction(self, run: ExtractionRun) -> ExtractionRun: ...
    def get_extraction(self, extraction_run_id: str) -> ExtractionRun | None: ...
    def create_review(self, review: EngineeringReview) -> EngineeringReview: ...
    def get_review(self, review_id: str) -> EngineeringReview | None: ...
    def save_review(self, review: EngineeringReview, expected_token: bytes) -> EngineeringReview: ...
    def confirm(self, review: EngineeringReview, commands: tuple[ConfirmedCommand, ...], expected_token: bytes) -> tuple[EngineeringReview, tuple[ConfirmedCommand, ...]]: ...
    def list_commands(self, review_id: str) -> tuple[ConfirmedCommand, ...]: ...
