"""Persistence contracts for engineering extraction review."""

from typing import Protocol
from backend.domain.engineering_review import ConfirmedCommand, EngineeringReview, ExtractionRun


class EngineeringReviewRepository(Protocol):
    def discover_extraction(self, run: ExtractionRun) -> ExtractionRun: ...
    def get_extraction(self, extraction_run_id: str) -> ExtractionRun | None: ...
    def create_review(self, review: EngineeringReview) -> EngineeringReview: ...
    def get_review(self, review_id: str) -> EngineeringReview | None: ...
    def save_review(self, review: EngineeringReview, expected_token: bytes) -> EngineeringReview: ...
    def confirm(self, review: EngineeringReview, commands: tuple[ConfirmedCommand, ...], expected_token: bytes) -> tuple[EngineeringReview, tuple[ConfirmedCommand, ...]]: ...
    def list_commands(self, review_id: str) -> tuple[ConfirmedCommand, ...]: ...
    def get_command(self, command_id: str) -> ConfirmedCommand | None: ...
    def claim_command(self, command_id: str, lease_id: str, lease_expires_at, now) -> ConfirmedCommand | None: ...
    def complete_command(self, command: ConfirmedCommand) -> ConfirmedCommand: ...
    def record_event(self, review_id: str, action: str, command_id: str | None = None,
                     failure_code: str | None = None, actor_id: str | None = None) -> None: ...
