"""Persistence and PageIndex discovery contracts for Manifest records."""

from typing import Protocol, runtime_checkable

from backend.domain.manifest import ManifestRecord, PageIndexState, TrainingState


class ManifestConcurrencyError(RuntimeError):
    """A Manifest mutation used a stale optimistic-concurrency token."""


@runtime_checkable
class ManifestRepository(Protocol):
    def discover(self, record: ManifestRecord) -> ManifestRecord: ...
    def get_version(self, document_version_id: str) -> ManifestRecord | None: ...
    def list_active_trained_markdown(self) -> tuple[ManifestRecord, ...]: ...
    def list_by_pageindex_states(self, *states: PageIndexState) -> tuple[ManifestRecord, ...]: ...
    def list_missing_workspace_mapping(self) -> tuple[ManifestRecord, ...]: ...
    def mark_training_state(self, document_version_id: str, state: TrainingState, expected_token: bytes) -> ManifestRecord: ...
    def mark_indexing_attempt(self, document_version_id: str, expected_token: bytes) -> ManifestRecord: ...
    def mark_indexed(self, document_version_id: str, workspace_document_id: str, expected_token: bytes) -> ManifestRecord: ...
    def mark_failed(self, document_version_id: str, error: str, expected_token: bytes) -> ManifestRecord: ...
    def mark_retired(self, document_version_id: str, expected_token: bytes) -> ManifestRecord: ...


PageIndexDiscoveryRepository = ManifestRepository
